// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitDatabaseRepo() *DatabaseRepository {
	databasePostgreSQL := NewDatabasePostgreSQL()
	databaseMySQL := NewDatabaseMySQL()
	databaseRepository := NewDatabaseRepository(databasePostgreSQL, databaseMySQL)
	return databaseRepository
}

func initFooBarService() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

// injector.go:

var fooSet = wire.NewSet(NewFooService, NewFooRepository)

var barSet = wire.NewSet(NewBarService, NewBarRepository)
